import { useState, type ReactElement } from 'react'
import { Sparkles } from 'lucide-react'
import type { AiProvidersState } from '@reflect/core'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Switch } from '@/components/ui/switch'
import { backfillAssetDescriptionsVisibly } from '@/lib/asset-backfill'
import { useGraph } from '@/providers/graph-provider'
import { useSettings } from '@/providers/settings-provider'
import { SettingsField } from './field'

/**
 * Settings → asset descriptions (Plan 20): a toggle for the automatic path
 * (describe new images/PDFs as they're added) plus an explicit "Describe
 * existing assets" backfill, gated behind a cost-warning confirmation because
 * an existing graph can hold many large or costly assets. Progress and final
 * state surface through the operations status UI.
 */
export function DescribeAssetsField(): ReactElement {
  const { settings, updateSettings } = useSettings()
  const { graph } = useGraph()
  const [confirming, setConfirming] = useState(false)
  const [running, setRunning] = useState(false)

  const hasProvider = settings.aiProviders.length > 0
  const generation = graph?.generation ?? null

  const runBackfill = async (): Promise<void> => {
    setConfirming(false)
    if (generation === null || running) {
      return
    }
    const providers: AiProvidersState = {
      providers: settings.aiProviders,
      defaultProviderId: settings.defaultAiProviderId,
    }
    setRunning(true)
    try {
      await backfillAssetDescriptionsVisibly(generation, providers)
    } finally {
      setRunning(false)
    }
  }

  return (
    <SettingsField
      legend="Describe assets"
      description="Reflect can describe images and PDFs in your assets so their contents are searchable. Descriptions are generated by your configured AI provider and may incur charges. Private and unreferenced files are skipped."
    >
      <div className="mt-3 flex items-center gap-3">
        <Switch
          aria-label="Describe new assets automatically"
          checked={settings.describeAssets}
          onCheckedChange={(checked) => updateSettings({ describeAssets: checked })}
        />
        <span className="text-xs text-text-muted">Describe new assets automatically</span>
      </div>
      <div className="mt-3">
        <Button
          type="button"
          variant="outline"
          size="sm"
          disabled={generation === null || !hasProvider || running}
          onClick={() => setConfirming(true)}
          className="text-text-secondary"
        >
          <Sparkles aria-hidden strokeWidth={1.75} className={running ? 'animate-pulse' : undefined} />
          {running ? 'Describing…' : 'Describe existing assets'}
        </Button>
        {!hasProvider ? (
          <p className="mt-2 text-xs text-text-muted">Add an AI provider to enable this.</p>
        ) : null}
      </div>
      {confirming ? (
        <Dialog open onOpenChange={(isOpen) => { if (!isOpen) setConfirming(false) }}>
          <DialogContent showCloseButton={false} className="max-w-sm">
            <DialogHeader>
              <DialogTitle>Describe existing assets?</DialogTitle>
              <DialogDescription>
                Every eligible image and PDF referenced by a non-private note will be sent to
                your configured AI provider, which may incur charges. Files already described are
                skipped.
              </DialogDescription>
            </DialogHeader>
            <DialogFooter>
              <Button type="button" variant="ghost" size="sm" onClick={() => setConfirming(false)}>
                Cancel
              </Button>
              <Button type="button" size="sm" onClick={() => void runBackfill()}>
                Describe assets
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      ) : null}
    </SettingsField>
  )
}
