packages:
  - apps/*
  - packages/*
  - design-system

allowBuilds:
  '@sentry/cli': true
  better-sqlite3: true
  esbuild: true
  simple-git-hooks: false
  spawn-sync: true

dedupePeers: true

strictPeerDependencies: true

ignoreWorkspaceRootCheck: true

minimumReleaseAgeExclude:
  - '@meowdown/*'
  - '@prosekit/*'
  - '@aria-ui/*'
  - '@ocavue/*'
  - '@post-embed/*'
  - '@prosemirror-adapter/*'
  - prosemirror-flat-list
  - prosemirror-view

blockExoticSubdeps: false
overrides:
  '@post-embed/types': https://pkg.pr.new/@post-embed/types@7bc1a3259420e2060f3183eec77557183abd7e66
  '@post-embed/schema': https://pkg.pr.new/@post-embed/schema@7bc1a3259420e2060f3183eec77557183abd7e66
  '@post-embed/exporter': https://pkg.pr.new/@post-embed/exporter@7bc1a3259420e2060f3183eec77557183abd7e66
  '@post-embed/elements': https://pkg.pr.new/@post-embed/elements@7bc1a3259420e2060f3183eec77557183abd7e66
  '@meowdown/core': https://pkg.pr.new/@meowdown/core@9dd89d2b472816ffe6f855fa6bcd90e9716b7c94
  '@meowdown/react': https://pkg.pr.new/@meowdown/react@9dd89d2b472816ffe6f855fa6bcd90e9716b7c94
  '@meowdown/markdown': https://pkg.pr.new/@meowdown/markdown@9dd89d2b472816ffe6f855fa6bcd90e9716b7c94
