packages:
  - apps/*
  - packages/*
  - design-system

allowBuilds:
  '@sentry/cli': true
  better-sqlite3: true
  esbuild: true
  simple-git-hooks: false
  spawn-sync: true

dedupePeers: true

strictPeerDependencies: true

ignoreWorkspaceRootCheck: true

minimumReleaseAgeExclude:
  - '@meowdown/*'
  - '@prosekit/*'
  - '@aria-ui/*'
  - '@ocavue/*'
  - '@post-embed/*'
  - '@prosemirror-adapter/*'
  - prosemirror-flat-list
  - prosemirror-view

# Development snapshots for meowdown; replace with releases when publishing.
blockExoticSubdeps: false
overrides:
  '@meowdown/core': https://pkg.pr.new/@meowdown/core@346867e5f1b5336c889e829b146a04fcc0c115c1
  '@meowdown/react': https://pkg.pr.new/@meowdown/react@346867e5f1b5336c889e829b146a04fcc0c115c1
  '@meowdown/markdown': https://pkg.pr.new/@meowdown/markdown@346867e5f1b5336c889e829b146a04fcc0c115c1

FIXME: the latest version of meowdown is being published to npm. Update the overrides above by commenting them out and update package.json
