/**
 * `@reflect/core` sync domain (Plan 12) — GitHub backup & sync over the Rust
 * git primitives: typed command bindings, the GitHub module (device flow,
 * token refresh, repo API), and the debounced sync engine.
 */
export {
  gitStatus,
  gitSetup,
  gitDisconnect,
  gitClone,
  gitCommitAll,
  gitFetch,
  gitRemoteHead,
  gitMergeRemote,
  gitPush,
  gitStatusSchema,
  commitOutcomeSchema,
  remoteDeltaSchema,
  remoteTipSchema,
  mergeOutcomeSchema,
  pushOutcomeSchema,
  skippedFileSchema,
  changedFileSchema,
  type GitCredential,
  type GitStatus,
  type CommitOutcome,
  type RemoteDelta,
  type RemoteTip,
  type MergeOutcome,
  type PushOutcome,
  type SkippedFile,
  type ChangedFile,
} from './commands.ts'
export {
  GITHUB_APP_CLIENT_ID,
  GITHUB_APP_SLUG,
  GITHUB_AUTH_SECRET,
  githubAppInstallUrl,
  isDeviceFlowConfigured,
  githubAuthSchema,
  saveGithubAuth,
  loadGithubAuth,
  clearGithubAuth,
  deviceFlowStart,
  deviceFlowPoll,
  runDeviceFlow,
  refreshGithubAuth,
  getGithubToken,
  githubCredential,
  parseGithubRemote,
  githubRemoteUrl,
  newRepoUrl,
  BACKUP_REPO_DESCRIPTION,
  createGithubRepo,
  getGithubRepo,
  getAuthenticatedUser,
  type GithubAuth,
  type DeviceFlowStart,
  type DevicePollResult,
  type RunDeviceFlowOptions,
  type GithubRepoRef,
  type GithubRepo,
  type GithubUser,
} from './github.ts'
export { createGist, updateGist, deleteGist, type PublishedGist, type GistFile } from './gists.ts'
export {
  clearHostCredential,
  loadHostCredential,
  remoteHost,
  saveHostCredential,
} from './host-credentials.ts'
export {
  createSyncEngine,
  isSyncError,
  type SyncEngine,
  type SyncEngineOptions,
  type SyncErrorKind,
  type SyncStatus,
} from './engine.ts'
